[package]
name = "keylime_agent"
version = "0.1.0"
authors = ["Pei Jia <leojia@bu.edu>"]

[dependencies]
futures = "0.1.24"
hyper = "0.12"
tokio-io = "0.1"
serde_json = "1.0"
pretty_env_logger = "0.2.0"
log = "0.4"
libc = "0.2.43"
serde = "1.0.80"
serde_derive = "1.0.80"
rustc-serialize = "0.3.24"
tempfile = "3.0.4"
openssl = "0.10.15"
hex = "0.3.2"
base64 = "0.9.3"
flate2 = "1.0.4"
serde_yaml = "0.8"
