[package]
authors = ["Keylime Authors"]
edition = "2018"
name = "keylime_agent"
version = "0.1.0"
license = "Apache-2.0"
description = "Rust agent for Keylime"
repository = "https://github.com/keylime/rust-keylime"

[[bin]]
name = "keylime_agent"
path = "src/main.rs"
doc = false

[[bin]]
name = "keylime_ima_emulator"
path = "src/ima_emulator.rs"
doc = false

[dependencies]
actix-web =  { version = "3", features = ["openssl"] }
base64 = "0.13"
cfg-if = "1"
compress-tools = "0.12"
flate2 = "1.0.4"
futures = "0.3.6"
hex = "0.4"
libc = "0.2.43"
log = "0.4"
openssl = "0.10.15"
pretty_env_logger = "0.4"
reqwest = {version = "0.10.8", features = ["json"]}
rust-ini = "0.17"
rustc-serialize = "0.3.24"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = { version = "1.0", features = ["raw_value"] }
static_assertions = "1"
tempfile = "3.0.4"
tokio = {version = "0.2", features = ["full"]}
tokio-io = "0.1"
tss-esapi = "7.0.0-beta.1"
thiserror = "1.0"
zmq = "0.9.2"
uuid = {version = "0.8", features = ["v4"]}

[dev-dependencies]
actix-rt = "2"
wiremock = "0.5"

[features]
# this should change to dev-dependencies when we have integration testing
testing = []
