[package]
authors = ["Keylime Authors"]
edition = "2018"
name = "keylime_agent"
version = "0.1.0"

[dependencies]
actix-web = "3"
base64 = "0.9.3"
flate2 = "1.0.4"
futures = "0.3.6"
hex = "0.3.2"
libc = "0.2.43"
log = "0.4"
openssl = "0.10.15"
pretty_env_logger = "0.2.0"
reqwest = {version = "0.10.8", features = ["json"]}
rust-ini = "0.12.1"
rustc-serialize = "0.3.24"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0"
tempfile = "3.0.4"
tokio = {version = "0.2", features = ["full"]}
tokio-io = "0.1"
tss-esapi = "4.0.9-alpha.1"
uuid = {version = "0.8", features = ["v4"]}
validators = "0.22.2"
validators-derive = "0.21.6"
# While functions are being added, we use the git repo version for now
# tss-esapi = "4.0.9-alpha.1"
tss-esapi = { git = "https://github.com/parallaxsecond/rust-tss-esapi", rev = "743b3a63385dd9960013e26f6a35d34d64b16498" }
